Fancier messages and wayyy faster asset detection
Too bad that now I have to find a way to pass other stuff like relative
paths too. Still better than having to wait 2:30 minutes to only parse
the JSON file every time.

diff --git a/minekiss b/minekiss
--- a/minekiss
+++ b/minekiss
@@ -1,5 +1,6 @@
-#! /bin/sh -e
+#! /bin/sh
 
+# TODO: Add some good error handling where needed
 # TODO: Properly manage native libraries by extracting them (https://wiki.vg/Game_Files)
 # TODO: Properly manage legacy and pre-1.6 assets
 # TODO: Add a rule reading system
@@ -9,12 +10,15 @@
 # TODO: Find a portable way of switching java versions or at least find a way to configure them
 # TODO: Refactor everything
 
-get_resource_url() {
-	printf "$RESOURCES_URL/$(printf "%s" "$1" | head -c 2)/$1"
-}
+# Bruh
+export LC_ALL="C"
 
 get_relative_resource_path() {
  printf "$(printf "%s" "$1" | head -c 2)/$1"
+}
+
+get_resource_url() {
+	printf "$RESOURCES_URL/$(get_relative_resource_path "$1")"
 }
 
 parse_libraries_from_metadata() {
@@ -24,8 +28,16 @@ parse_libraries_from_metadata() {
 }
 
 error() {
-	printf "$1\n"
+	printf "X $1\n"
 	exit 1
+}
+
+info() {
+	printf -- "-> $1\n"
+}
+
+warning() {
+	printf "! $1\n"
 }
 
 download() {
@@ -37,43 +49,35 @@ download() {
 	VERSION_MANIFEST_FILE="$CACHE_DIR/version_manifest.json"
 	ASSET_INDEX_FILE="$ASSETS_DIR/indexes/$SELECTED_VERSION.json"
 
-	printf "Fetching the version manifest...\n"
+	info "Fetching the latest version manifest..."
+
 	mkdir -p "$(dirname "$VERSION_MANIFEST_FILE")"
-	curl -s "$VERSION_MANIFEST_URL" > "$VERSION_MANIFEST_FILE"
-
-	if [ "$?" != 0 ] 
-	then
-		# TODO: Implement an offline mode.
-		error "Unable to fetch the manifest."
-	fi
-
-
+	curl -s "$VERSION_MANIFEST_URL" > "$VERSION_MANIFEST_FILE" || error "Unable to fetch the latest manifest!"
+	
 	VERSION_METADATA_URL="$(jq -r ".versions[] | select(.id == \"$SELECTED_VERSION\").url" < "$VERSION_MANIFEST_FILE")"
 
-	if [ -f "$VERSION_METADATA_FILE" ] && [ "$VERSION_METADATA_URL" != "" ]
+	if [ "$VERSION_METADATA_URL" == "" ]
 	then
-		printf "Validating the current version matadata...\n"
+			error "Invalid version id!"
+	fi
+
+	if [ -f "$VERSION_METADATA_FILE" ]
+	then
+		info "Validating the current version metadata..."
 
 		# The SHA1 is for some reason only encoded into the version metadata path.
 		# URL format: https://launchermeta.mojang.com/v1/packages/SHA/VERSION.json
 		VERSION_METADATA_SHA1="$(basename "$(dirname "$VERSION_METADATA_URL")")"
 
-		# sha1sum returns the name of the file alongside the actual SHA1
-		VERSION_METADATA_CURRENT_SHA1="$(sha1sum "$VERSION_METADATA_FILE" | cut -d " " -f 1)"
+		printf "%s  %s\n" "$VERSION_METADATA_SHA1" "$VERSION_METADATA_FILE" | sha1sum -c 1>/dev/null 2>&1
 
-		if [ "$VERSION_METADATA_CURRENT_SHA1" != $VERSION_METADATA_SHA1 ]
+		if [ $? != 0 ]
 		then
-			printf "Validation failed! Redownloading...\n"
+			info "Validation failed! Redownloading..."
 			curl -s "$VERSION_METADATA_URL" > "$VERSION_METADATA_FILE"
 		fi
 	else
-		if [ "$VERSION_METADATA_URL" == "" ]
-		then
-			printf "Invalid version id.\n"
-			exit 1
-		fi
-
-		printf "Fetching the version metadata file...\n"
+		info "Fetching the version metadata file..."
 		mkdir -p "$(dirname "$VERSION_METADATA_FILE")"
 		curl -s "$VERSION_METADATA_URL" > "$VERSION_METADATA_FILE"
 	fi
@@ -82,20 +86,21 @@ download() {
 
 	if [ -f "$VERSION_CLIENT_FILE" ]
 	then
-		printf "Validating the client jar...\n"
+		info "Validating the client jar..."
 
 		VERSION_CLIENT_SHA1="$(jq -r ".downloads.client.sha1" < "$VERSION_METADATA_FILE")"
 
-		# sha1sum returns the name of the file alongside the actual SHA1
-		VERSION_CLIENT_CURRENT_SHA1="$(sha1sum "$VERSION_CLIENT_FILE" | cut -d " " -f 1)"
+		printf "%s  %s\n" "$VERSION_CLIENT_SHA1" "$VERSION_CLIENT_FILE" | sha1sum -c 1>/dev/null 2>&1
 
-		if [ "$VERSION_CLIENT_CURRENT_SHA1" != "$VERSION_CLIENT_SHA1" ]
+		if [ $? != 0 ]
 		then
-			printf "Validation failed! Redownloading...\n"
+			info "Validation failed! Redownloading..."
 			curl -s "$VERSION_CLIENT_URL" > "$VERSION_CLIENT_FILE"
 		fi
 	else
-		printf "Downloading the client jar...\n"
+		info "Downloading the client jar..."
+		# We don't run mkdir here because the client will be downloaded in the same
+		# directory of the version metadata.
 		curl -s "$VERSION_CLIENT_URL" > "$VERSION_CLIENT_FILE"
 	fi
 
@@ -103,13 +108,13 @@ download() {
 
 	if [ -f "$ASSET_INDEX_FILE" ]
 	then
-		printf "Validating the game's asset index...\n"
+		info "Validating the game's asset index..."
 
 		ASSET_INDEX_SHA1="$(jq -r ".assetIndex.sha1" < "$VERSION_METADATA_FILE")"
 
-		# sha1sum returns the name of the file alongside the actual SHA1
-		ASSET_INDEX_CURRENT_SHA1="$(sha1sum "$ASSET_INDEX_FILE" | cut -d " " -f 1)"
-		if [ "$ASSET_INDEX_CURRENT_SHA1" != "$ASSET_INDEX_SHA1" ]
+		printf "%s  %s\n" "$ASSET_INDEX_SHA1"  "$ASSET_FILE" | sha1sum -c 1>/dev/null 2>&1
+
+		if [ $? == 0 ]
 		then
 			printf "Validation failed! Redownloading...\n"
 			curl -s "$ASSET_INDEX_URL" > "$ASSET_INDEX_FILE"
@@ -119,52 +124,28 @@ download() {
 
 		mkdir -p "$(dirname $ASSET_INDEX_FILE)"
 		curl -s "$ASSET_INDEX_URL" > "$ASSET_INDEX_FILE"
-
-		if [ "$?" != 0 ]
-		then
-			# TODO: Implement an offline mode.
-			error "Unable to fetch the game's asset index."
-		fi
 	fi
 
 	printf "Validating the game's assets...\n"
 
-	jq -r ".objects | keys[]" < "$ASSET_INDEX_FILE" | while read -r ASSET_GAME_PATH
+	# TODO: Add support for the older assets formats.
+	# TODO: Add a nice and clean way of displaying the relative path of the
+	# downloading asset.
+	jq -r ".objects[] | .hash + \" \" + \"$ASSETS_DIR/objects/\" + .hash[0:2] + \"/\" + .hash" < "$ASSET_INDEX_FILE" | sha1sum -c 2> /dev/null | grep FAILED | cut -d ":" -f 1 | while read -r FILE_PATH
 	do
-		ASSET_SHA1="$(jq -r ".objects.\"$ASSET_GAME_PATH\".hash" < "$ASSET_INDEX_FILE")"
+		ASSET_SHA1="$(basename "$FILE_PATH")"
 
-		ASSET_IS_VIRTUAL="$(jq -r ".virtual // .map_to_resources" < "$ASSET_INDEX_FILE")"
-
-		if  [ "$ASSET_IS_VIRTUAL" == true ]
-		then
-			ASSET_FILE="$ASSETS_DIR/virtual/legacy/$ASSET_GAME_PATH"
-		else
-			ASSET_FILE="$ASSETS_DIR/objects/$(get_relative_resource_path "$ASSET_SHA1")"
-		fi
-
-		if [ -f "$ASSET_FILE" ]
-		then
-			ASSET_CURRENT_SHA1="$(sha1sum "$ASSET_FILE" | cut -d " " -f 1)"
-
-			printf "Validating \"%s\"...\n" "$ASSET_GAME_PATH"
-
-			if [ "$ASSET_CURRENT_SHA1" != "$ASSET_SHA1" ]
-			then
-				printf "Redownloading \"%s\"...\n" "$ASSET_GAME_PATH"
-
-				mkdir -p "$(dirname "$ASSET_FILE")"
-				curl -s "$RESOURCES_URL/$(get_relative_resource_path "$ASSET_SHA1")" > "$ASSET_FILE"
-			fi
-		else
-			printf "Downloading \"$ASSET_GAME_PATH\"...\n"
-			mkdir -p "$(dirname "$ASSET_FILE")"
-			curl -s "$RESOURCES_URL/$(get_relative_resource_path "$ASSET_SHA1")" > "$ASSET_FILE"
-		fi
+		info "Downloading \"$ASSET_SHA1\"..."
+		mkdir -p "$(dirname "$FILE_PATH")"
+		curl -s "$(get_resource_url "$ASSET_SHA1")" > "$FILE_PATH"
 	done
 
-	printf "Validating the game's libraries...\n"
+	info "Validating the game's libraries..."
 
-		parse_libraries_from_metadata < "$VERSION_METADATA_FILE" | while read -r ARTIFACT_OBJECT
+	# TODO: Decompress properly the native libraries into a specialized directory.
+	# TODO: Make the parsing faster and cleaner using an approach similar to the
+	# above.
+	parse_libraries_from_metadata < "$VERSION_METADATA_FILE" | while read -r ARTIFACT_OBJECT
 	do
 		LIBRARY_RELATIVE_PATH="$(printf "%s" "$ARTIFACT_OBJECT" | jq -r ".path")"
 		LIBRARY_SHA1="$(printf "%s" "$ARTIFACT_OBJECT" | jq -r ".sha1")"
@@ -176,19 +157,19 @@ download() {
 
 		LIBRARY_URL="$(printf "%s" "$ARTIFACT_OBJECT" | jq -r ".url")"
 
-		if [ -f "$LIBRARIES_DIR/LIBRARY_RELATIVE_PATH" ]
+		if [ -f "$LIBRARY_FILE" ]
 		then
-			printf "Validating \"%s\"...\n" "$LIBRARY_FILE_NAME"
+			info "Validating \"$LIBRARY_FILE_NAME\"..."
 
 			LIBRARY_CURRENT_SHA1="$(sha1sum "$LIBRARY_FILE" | cut -d " " -f 1)"
 
 			if [ "$LIBRARY_CURRENT_SHA1" != "$LIBRARY_SHA1" ]
 			then
-				printf "Redownloading \"%s\"...\n" "$LIBRARY_FILE_NAME"
+				info "Redownloading \"$LIBRARY_FILE_NAME\"..."
 				curl -s "$LIBRARY_URL" > "$LIBRARY_FILE"
 			fi
 		else
-			printf "Downloading \"%s\"...\n" "$LIBRARY_FILE_NAME"
+			info "Downloading \"$LIBRARY_FILE_NAME\"..."
 			curl -s "$LIBRARY_URL" > "$LIBRARY_FILE"
 		fi
 	done
@@ -274,7 +255,7 @@ if [ "$1" == "download" ]
 then
 	if [ "$2" != "" ]
 	then
-		download "$2"
+		download "$2" && info "Download finished."
 	else
 		printf "Usage: $0 download ID\n"
 		printf "Downloads and verifies the specified mincraft version into minekiss' cache directory.\n"
@@ -298,7 +279,7 @@ if [ "$1" != "" ]
 then
 	printf "Unrecognized command: \"$1\"\n"
 else
-	printf "minekiss - A minecraft instance system with a powerful package manager.\n"
+	printf "minekiss - A simple minecraft launcher written entirely in POSIX shell.\n"
 	printf "Available commands:\n"
 	printf " - download: Downloads and verifies the specified minecraft version into minekiss' cache directory.\n"
 	printf " - start: Runs the specified minecraft version (if dowloaded) into the current drectory.\n"
